[package]
name = "crabsplit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.1"
chrono = "0.4.31"
tzfile = "0.1.3"
serde = "1.0.195"
serde_json = "1.0"
